### ISSUE TITLE
FatalThrowableError in Facade.php line 217: Call to undefined method Laravelista\Ekko\Ekko::isAcxtiveRoute()

### ISSUE THREAD

**Issue by dukenst2006** [dameety/laravel-church-sermons-app#1]
Hello @dameety,
Congratulations for this great work, i installed the app, when i try to login as admin it's give this error
FatalThrowableError in Facade.php line 217: Call to undefined method Laravelista\Ekko\Ekko::isAcxtiveRoute()
please considere this screenshot above.
Any idea ?

Regards
![screen](https://cloud.githubusercontent.com/assets/7965394/23980231/b982d068-09bb-11e7-9e67-1c916259432d.png)

**Comment by dameety** [comment]
Greetings  @dukenst2006  The error is coming from the laravel ekko package. Please visit the doc on this link https://github.com/laravelista/Ekko. The package has been updated since i included it in the app so enabling it must have changed. Just follow the instructions on how to use it on the doc page and all should be fine.
